In [1]:
import torch

### **1D Tensor**

In [2]:
x = torch.FloatTensor([0.,1.,0.,8.])
x

tensor([0., 1., 0., 8.])

In [3]:
x.shape

torch.Size([4])

### **3D Tensor**

In [4]:
x = torch.FloatTensor([[[0.,1.], [1.,0.,]],
                       [[1.,1.], [0.,0.]]])
x

tensor([[[0., 1.],
         [1., 0.]],

        [[1., 1.],
         [0., 0.]]])

In [5]:
x.shape

torch.Size([2, 2, 2])

### **Addition**

In [9]:
x = torch.FloatTensor([[0.,1.], [1.,0.]])
y = torch.FloatTensor([[1.,1.], [0.,0.]])
x+y

tensor([[1., 2.],
        [1., 0.]])

In [10]:
x = torch.FloatTensor([[0.,1.],[1.,0.]])
y = torch.FloatTensor([3])
x+y

tensor([[3., 4.],
        [4., 3.]])

### **Multiplication**

In [12]:
x = torch.FloatTensor([[0.,1.], [1.,0.]])
y = torch.FloatTensor([[1.,1.], [0.,0.]])
x.matmul(y) ##matrix mult

tensor([[0., 0.],
        [1., 1.]])

In [13]:
x*y ##element-wise

tensor([[0., 1.],
        [0., 0.]])

In [14]:
x.mul(y) ##element-wise

tensor([[0., 1.],
        [0., 0.]])

### **Mean**

In [15]:
x = torch.FloatTensor([[2.,2.], [4.,4.]])

In [16]:
print(x.mean())
print(x.mean(dim=0))
print(x.mean(dim=1))

tensor(3.)
tensor([3., 3.])
tensor([2., 4.])


### **Concatenate**

In [17]:
x = torch.FloatTensor([[2.,2.], [4.,4.]])
y = torch.FloatTensor([[5.,5.], [10.,10.]])

In [21]:
print(torch.cat([x,y], dim=0))
print(torch.cat([x,y], dim=1))

tensor([[ 2.,  2.],
        [ 4.,  4.],
        [ 5.,  5.],
        [10., 10.]])
tensor([[ 2.,  2.,  5.,  5.],
        [ 4.,  4., 10., 10.]])


### **View**

In [22]:
x = torch.FloatTensor([[[0.,1.], [1.,0.]],
                       [[1.,1.], [0.,0.]]])
x.shape

torch.Size([2, 2, 2])

In [23]:
x.view(-1,2).shape

torch.Size([4, 2])

In [24]:
x.view(-1,1,2).shape

torch.Size([4, 1, 2])

### **Squeeze**
- *squeeze*: reduce by 1D
- *unsqueeze*: increase by 1D

In [25]:
x = torch.FloatTensor([[[0.], [1.], [2.]]])
x.shape

torch.Size([1, 3, 1])

In [27]:
torch.squeeze(x, dim=0).shape

torch.Size([3, 1])

In [28]:
torch.squeeze(x, dim=2).shape

torch.Size([1, 3])

In [29]:
torch.unsqueeze(x, dim=0).shape

torch.Size([1, 1, 3, 1])

In [30]:
torch.unsqueeze(x, dim=2).shape

torch.Size([1, 3, 1, 1])