## **Gradient**

In [1]:
import torch

a = torch.tensor([2.], requires_grad=True)
b = torch.tensor([6.], requires_grad=True)

In [3]:
Q = 3*a**3 - b**2
Q # loss

tensor([-12.], grad_fn=<SubBackward0>)

In [4]:
print(a.grad)
print(b.grad)

None
None


In [5]:
Q.backward()

In [6]:
print(a.grad)
print(b.grad)

tensor([36.])
tensor([-12.])


## **Optimizer**

In [8]:
# Stochastic Gradient Descent
# optimizer = torch.optim.SGD(params=model.parameters(), lr=1e-3) 

In [ ]:
# Momentum
# optimizer = torch.optim.SGD(params=model.parameters(), lr=1e-3, momentum=0.9)

In [ ]:
# Adaptive Gradient
# optimizer = torch.optim.Adagrad(params=model.parameters(), lr=1e-3)

In [ ]:
# RMSProp
# optimizer = torch.optim.RMSprop(params=model.parameters(), lr=1e-3, alpha=0.99)

In [ ]:
# Adaptive Moment Estimation (ADAM)
# optimizer = torch.optim.Adam(params=model.parameters(), lr=1e-3,betas=(0.9, 0.999))